<a href="https://colab.research.google.com/github/KahPrisco/Bootcamp/blob/main/Banco_Relacional_(SQL).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.11/dist-packages (9.3.0)

In [ ]:
import mysql.connector
import pandas as pd

In [ ]:
host = '34.44.184.94'
user = 'root'
password = ''
database = 'loja_jogos'

In [ ]:
!curl ipecho.net/plain

34.135.246.47

In [ ]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com o banco de dados
cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'show tables;' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
tabelas = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(tabelas) # exibindo a tabela pandas
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

  Tables_in_loja_jogos
0           Categorias
1             Clientes
2         Fornecedores
3          ItensPedido
4                Jogos
5              Pedidos

In [ ]:
'''
Categorias
'''
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com o banco de dados

cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'select * from Categorias;' #Query ou consulta desejada
cursor.execute(query) #Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
categorias = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(categorias) #exibindo a tabela pandas
cursor.close() #fechando o cursor
connection.close() #fechando a conexão

    id_categoria nome_categoria
0              1           Ação
1              2       Aventura
2              3            RPG
3              4        Corrida
4              5        Esporte
5              6     Estratégia
6              7      Simulação
7              8         Terror
8              9         Puzzle
9             10            FPS
10            11     Plataforma
11            12  Battle Royale
12            13           MOBA
13            14         MMORPG
14            15          Indie

In [ ]:
'''
Fazendo o uploado do arquivo tratado diretamente pelo
Colab, sem passar pela máquina local

'''
from google.colab import auth
auth.authenticate_user()

project_id = 'quixotic-strand-454923-q7'
!gcloud config set project {project_id}

from google.cloud import storage
client = storage.Client()

bucket_name = 'banco-jogos-kauane'
bucket = client.bucket(bucket_name)

categorias.to_csv('tabelas_lojajogo_categorias.csv', index=False)

source_file_name = 'tabelas_lojajogo_categorias.csv'
destination_blob_name = 'tabelas_lojajogo/tabelas_lojajogo_categorias.csv'  # Corrigido!

blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

Updated property [core/project].

In [ ]:
'''
Jogos
'''
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com o banco de dados

cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'select * from Jogos;' #Query ou consulta desejada
cursor.execute(query) #Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
jogos = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(jogos) #exibindo a tabela pandas
cursor.close() #fechando o cursor
connection.close() #fechando a conexão

,id_jogo,nome,preco,estoque,id_categoria,id_fornecedor
0,1,Assassin’s Creed Valhalla,199.90,25,1,1
1,2,FIFA 23,249.90,30,5,2
2,3,Final Fantasy VII Remake,299.90,15,3,3
3,4,GTA V,149.90,40,1,4
4,5,Skyrim,129.90,12,3,5
5,6,God of War Ragnarök,349.90,10,1,6
6,7,Halo Infinite,299.90,8,10,7
7,8,Zelda: BOTW,299.90,20,2,8
8,9,Call of Duty: MWII,299.90,18,10,9
9,10,Resident Evil 4,279.90,15,8,10
10,11,Elden Ring,299.90,17,3,11
11,12,Total War: Warhammer III,199.90,6,6,12
12,13,Cyberpunk 2077,199.90,9,1,13
13,14,eFootball Plus 2024,0.00,100,5,14
14,15,Fortnite Pack,0.00,100,12,15

In [ ]:
'''
Fazendo o uploado do arquivo tratado diretamente pelo
Colab, sem passar pela máquina local

'''
from google.colab import auth
auth.authenticate_user()

project_id = 'quixotic-strand-454923-q7'
!gcloud config set project {project_id}

from google.cloud import storage
client = storage.Client()

bucket_name = 'banco-jogos-kauane'
bucket = client.bucket(bucket_name)

#mudar aqui
jogos.to_csv('tabelas_lojajogo_jogos.csv', index=False)

source_file_name = 'tabelas_lojajogo_jogos.csv'
destination_blob_name = 'tabelas_lojajogo/tabelas_lojajogo_jogos.csv'  # Corrigido!

blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

Updated property [core/project].

In [ ]:
'''
Fornecedores
'''
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com o banco de dados

cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'select * from Fornecedores;' #Query ou consulta desejada
cursor.execute(query) #Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
fornecedores = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(fornecedores) #exibindo a tabela pandas
cursor.close() #fechando o cursor
connection.close() #fechando a conexão

    id_fornecedor  nome_fornecedor     telefone                   email
0               1          Ubisoft  11999990001     contato@ubisoft.com
1               2  Electronic Arts  11999990002          contato@ea.com
2               3      Square Enix  11999990003  contato@squareenix.com
3               4   Rockstar Games  11999990004    contato@rockstar.com
4               5         Bethesda  11999990005    contato@bethesda.com
5               6             Sony  11999990006        contato@sony.com
6               7        Microsoft  11999990007   contato@microsoft.com
7               8         Nintendo  11999990008    contato@nintendo.com
8               9       Activision  11999990009  contato@activision.com
9              10           Capcom  11999990010      contato@capcom.com
10             11     Bandai Namco  11999990011      contato@bandai.com
11             12             SEGA  11999990012        contato@sega.com
12             13       CD Projekt  11999990013   contato@cdprojekt.com
13             14           Konami  11999990014      contato@konami.com
14             15       Epic Games  11999990015   contato@epicgames.com

In [ ]:
'''
Fazendo o uploado do arquivo tratado diretamente pelo
Colab, sem passar pela máquina local

'''
from google.colab import auth
auth.authenticate_user()

project_id = 'quixotic-strand-454923-q7'
!gcloud config set project {project_id}

from google.cloud import storage
client = storage.Client()

bucket_name = 'banco-jogos-kauane'
bucket = client.bucket(bucket_name)

#mudar aqui
fornecedores.to_csv('tabelas_lojajogo_fornecedores.csv', index=False)

source_file_name = 'tabelas_lojajogo_fornecedores.csv'
destination_blob_name = 'tabelas_lojajogo/tabelas_lojajogo_fornecedores.csv'

blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

Updated property [core/project].

In [ ]:
'''
Clientes
'''
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com o banco de dados

cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'select * from Clientes;' #Query ou consulta desejada
cursor.execute(query) #Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
clientes = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(clientes) #exibindo a tabela pandas
cursor.close() #fechando o cursor
connection.close() #fechando a conexão

    id_cliente             nome                      email     telefone
0            1   Lucas Ferreira   lucas.ferreira@email.com  11911110001
1            2      Ana Beatriz      ana.beatriz@email.com  11911110002
2            3     Carlos Silva     carlos.silva@email.com  11911110003
3            4   Fernanda Souza   fernanda.souza@email.com  11911110004
4            5       João Pedro       joao.pedro@email.com  11911110005
5            6  Larissa Andrade  larissa.andrade@email.com  11911110006
6            7     Gabriel Lima     gabriel.lima@email.com  11911110007
7            8   Mariana Duarte   mariana.duarte@email.com  11911110008
8            9  Vinícius Santos  vinicius.santos@email.com  11911110009
9           10  Juliana Martins  juliana.martins@email.com  11911110010
10          11     Rafael Gomes     rafael.gomes@email.com  11911110011
11          12   Isabela Castro   isabela.castro@email.com  11911110012
12          13     Thiago Costa     thiago.costa@email.com  11911110013
13          14     Camila Rocha     camila.rocha@email.com  11911110014
14          15   Daniel Almeida   daniel.almeida@email.com  11911110015

In [ ]:
'''
Fazendo o uploado do arquivo tratado diretamente pelo
Colab, sem passar pela máquina local

'''
from google.colab import auth
auth.authenticate_user()

project_id = 'quixotic-strand-454923-q7'
!gcloud config set project {project_id}

from google.cloud import storage
client = storage.Client()

bucket_name = 'banco-jogos-kauane'
bucket = client.bucket(bucket_name)

#mudar aqui
clientes.to_csv('tabelas_lojajogo_clientes.csv', index=False)

source_file_name = 'tabelas_lojajogo_clientes.csv'
destination_blob_name = 'tabelas_lojajogo/tabelas_lojajogo_clientes.csv'

blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

Updated property [core/project].

In [ ]:
'''
Pedidos
'''
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com o banco de dados

cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'select * from Pedidos;' #Query ou consulta desejada
cursor.execute(query) #Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
pedidos = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(pedidos) #exibindo a tabela pandas
cursor.close() #fechando o cursor
connection.close() #fechando a conexão

    id_pedido data_pedido  id_cliente
0           1  2025-04-01           1
1           2  2025-04-02           2
2           3  2025-04-03           3
3           4  2025-04-03           4
4           5  2025-04-04           5
5           6  2025-04-04           6
6           7  2025-04-05           7
7           8  2025-04-05           8
8           9  2025-04-06           9
9          10  2025-04-06          10
10         11  2025-04-07          11
11         12  2025-04-08          12
12         13  2025-04-08          13
13         14  2025-04-09          14
14         15  2025-04-09          15

In [ ]:
'''
Fazendo o uploado do arquivo tratado diretamente pelo
Colab, sem passar pela máquina local

'''
from google.colab import auth
auth.authenticate_user()

project_id = 'quixotic-strand-454923-q7'
!gcloud config set project {project_id}

from google.cloud import storage
client = storage.Client()

bucket_name = 'banco-jogos-kauane'
bucket = client.bucket(bucket_name)

#mudar aqui
pedidos.to_csv('tabelas_lojajogo_pedidos.csv', index=False)

source_file_name = 'tabelas_lojajogo_pedidos.csv'
destination_blob_name = 'tabelas_lojajogo/tabelas_lojajogo_pedidos.csv'

blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

Updated property [core/project].

In [ ]:
'''
Itens Pedido
'''
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com o banco de dados

cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'select * from ItensPedido;' #Query ou consulta desejada
cursor.execute(query) #Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
itensPedido = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(itensPedido) #exibindo a tabela pandas
cursor.close() #fechando o cursor
connection.close() #fechando a conexão

    id_item  id_pedido  id_jogo  quantidade preco_unitario
0         1          1        1           1         199.90
1         2          2        2           1         249.90
2         3          3        3           1         299.90
3         4          4        4           1         149.90
4         5          5        5           2         129.90
5         6          6        6           1         349.90
6         7          7        7           1         299.90
7         8          8        8           1         299.90
8         9          9        9           1         299.90
9        10         10       10           1         279.90
10       11         11       11           1         299.90
11       12         12       12           1         199.90
12       13         13       13           1         199.90
13       14         14       14           1          79.90
14       15         15       15           1          49.00

In [ ]:
'''
Fazendo o uploado do arquivo tratado diretamente pelo
Colab, sem passar pela máquina local

'''
from google.colab import auth
auth.authenticate_user()

project_id = 'quixotic-strand-454923-q7'
!gcloud config set project {project_id}

from google.cloud import storage
client = storage.Client()

bucket_name = 'banco-jogos-kauane'
bucket = client.bucket(bucket_name)

#mudar aqui
itensPedido.to_csv('tabelas_lojajogo_itensPedido.csv', index=False)

source_file_name = 'tabelas_lojajogo_itensPedido.csv'
destination_blob_name = 'tabelas_lojajogo/tabelas_lojajogo_itensPedido.csv'

blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

Updated property [core/project].