<a href="https://colab.research.google.com/github/KahPrisco/Bootcamp/blob/main/Kauane_Prisco_Primeiro_Projeto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Será necessário converte o DataFrame em listas, onde cada coluna será uma lista.
Será necessario realizar uma limpeza dos dados, removendo ou corrigindo valores inválidos, como:
Remover valores NaN ou strings vazias.
Garantir que os tipos de dados estejam corretos:
O campo salário deve ser convertido para o tipo float.
O campo idade deve ser convertido para o tipo int.
O sistema deve autenticar o usuário no Google Cloud usando a biblioteca google-cloud-storage.
O sistema deve realizar o upload do arquivo tratado para um bucket no Google Cloud Storage.
O arquivo tratado deve ser salvo no formato CSV dentro do bucket com o nome apropriado

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://storage.googleapis.com/projeto-kauane-prisco-1/dados-brutos/tabela_funcionarios.csv')

In [ ]:
display(df)

        nome  idade  salario        cargo
0     Carlos   34.0   3500.0     Analista
1      Maria   45.0   4500.0      Gerente
2       João   23.0      NaN   Assistente
3        Ana    NaN   5000.0  Coordenador
4      Lucas   30.0   3900.0          NaN
5      Paula   29.0   4200.0   Supervisor
6     Renato   56.0   5500.0      Diretor
7   Fernanda    NaN      NaN   Assistente
8    Marcelo   41.0   4800.0     Analista
9    Luciana   25.0   4200.0  Coordenador
10   Ricardo   38.0   5200.0      Gerente
11   Adriana   43.0   5500.0   Assistente
12      José   29.0   4800.0          NaN
13    Camila   34.0   5000.0     Analista
14    Rafael    NaN      NaN      Gerente
15     Paulo   22.0   3500.0  Coordenador
16     Carla   41.0   4200.0   Supervisor
17   Eduardo   50.0   5000.0   Assistente
18   Larissa   35.0   6000.0      Gerente
19     Mário   28.0   3900.0  Coordenador

In [ ]:
nome = list(df.nome)
idade = list(df.idade)
salario = list(df.salario)
cargo = list(df.cargo)
print(nome)
print(idade)
print(salario)
print(cargo)

['Carlos', 'Maria', 'João', 'Ana', 'Lucas', 'Paula', 'Renato', 'Fernanda', 'Marcelo', 'Luciana', 'Ricardo', 'Adriana', 'José', 'Camila', 'Rafael', 'Paulo', 'Carla', 'Eduardo', 'Larissa', 'Mário']
[34.0, 45.0, 23.0, nan, 30.0, 29.0, 56.0, nan, 41.0, 25.0, 38.0, 43.0, 29.0, 34.0, nan, 22.0, 41.0, 50.0, 35.0, 28.0]
[3500.0, 4500.0, nan, 5000.0, 3900.0, 4200.0, 5500.0, nan, 4800.0, 4200.0, 5200.0, 5500.0, 4800.0, 5000.0, nan, 3500.0, 4200.0, 5000.0, 6000.0, 3900.0]
['Analista', 'Gerente', 'Assistente', 'Coordenador', nan, 'Supervisor', 'Diretor', 'Assistente', 'Analista', 'Coordenador', 'Gerente', 'Assistente', nan, 'Analista', 'Gerente', 'Coordenador', 'Supervisor', 'Assistente', 'Gerente', 'Coordenador']

In [ ]:
dados_tratados = []

for x, y, z, n in zip(nome, idade, salario, cargo):
    dados_tratados.append([x, y, z, n])

for index,linha in enumerate(dados_tratados):
  print(index,linha)

0 ['Carlos', 34.0, 3500.0, 'Analista']
1 ['Maria', 45.0, 4500.0, 'Gerente']
2 ['João', 23.0, nan, 'Assistente']
3 ['Ana', nan, 5000.0, 'Coordenador']
4 ['Lucas', 30.0, 3900.0, nan]
5 ['Paula', 29.0, 4200.0, 'Supervisor']
6 ['Renato', 56.0, 5500.0, 'Diretor']
7 ['Fernanda', nan, nan, 'Assistente']
8 ['Marcelo', 41.0, 4800.0, 'Analista']
9 ['Luciana', 25.0, 4200.0, 'Coordenador']
10 ['Ricardo', 38.0, 5200.0, 'Gerente']
11 ['Adriana', 43.0, 5500.0, 'Assistente']
12 ['José', 29.0, 4800.0, nan]
13 ['Camila', 34.0, 5000.0, 'Analista']
14 ['Rafael', nan, nan, 'Gerente']
15 ['Paulo', 22.0, 3500.0, 'Coordenador']
16 ['Carla', 41.0, 4200.0, 'Supervisor']
17 ['Eduardo', 50.0, 5000.0, 'Assistente']
18 ['Larissa', 35.0, 6000.0, 'Gerente']
19 ['Mário', 28.0, 3900.0, 'Coordenador']

In [ ]:
for index, linha in enumerate(dados_tratados):
    if any(elemento != elemento for elemento in linha):  # Verifica se há NaN na linha
        print(f'\n{index}: {linha}')

2: ['João', 23.0, nan, 'Assistente']

3: ['Ana', nan, 5000.0, 'Coordenador']

4: ['Lucas', 30.0, 3900.0, nan]

7: ['Fernanda', nan, nan, 'Assistente']

12: ['José', 29.0, 4800.0, nan]

14: ['Rafael', nan, nan, 'Gerente']

In [ ]:
dados_tratados.pop(14)
dados_tratados.pop(12)
dados_tratados.pop(7)
dados_tratados.pop(4)
dados_tratados.pop(3)
dados_tratados.pop(2)

['João', 23.0, nan, 'Assistente']

In [ ]:
for index,linha in enumerate(dados_tratados):
  print(index,linha)

0 ['Carlos', 34.0, 3500.0, 'Analista']
1 ['Maria', 45.0, 4500.0, 'Gerente']
2 ['Paula', 29.0, 4200.0, 'Supervisor']
3 ['Renato', 56.0, 5500.0, 'Diretor']
4 ['Marcelo', 41.0, 4800.0, 'Analista']
5 ['Luciana', 25.0, 4200.0, 'Coordenador']
6 ['Ricardo', 38.0, 5200.0, 'Gerente']
7 ['Adriana', 43.0, 5500.0, 'Assistente']
8 ['Camila', 34.0, 5000.0, 'Analista']
9 ['Paulo', 22.0, 3500.0, 'Coordenador']
10 ['Carla', 41.0, 4200.0, 'Supervisor']
11 ['Eduardo', 50.0, 5000.0, 'Assistente']
12 ['Larissa', 35.0, 6000.0, 'Gerente']
13 ['Mário', 28.0, 3900.0, 'Coordenador']

In [ ]:
#Criando listas com nome, idade, salario e cargo.
'''
Garantir que os tipos de dados estejam corretos:
O campo salário deve ser convertido para o tipo float.
O campo idade deve ser convertido para o tipo int.
'''
nome = []
idade = []
salario = []
cargo = []

for linha in dados_tratados:
    nome.append(linha[0])
    idade.append(int(float(linha[1])))
    salario.append(float(linha[2]))
    cargo.append(linha[3])

# Exibindo as listas
print("nome:", nome)
print(type(nome[0]))
print("idade:", idade)
print(type(idade[0]))
print("salario:", salario)
print(type(salario[0]))
print("cargo:", cargo)
print(type(cargo[0]))

nome: ['Carlos', 'Maria', 'Paula', 'Renato', 'Marcelo', 'Luciana', 'Ricardo', 'Adriana', 'Camila', 'Paulo', 'Carla', 'Eduardo', 'Larissa', 'Mário']
<class 'str'>
idade: [34, 45, 29, 56, 41, 25, 38, 43, 34, 22, 41, 50, 35, 28]
<class 'int'>
salario: [3500.0, 4500.0, 4200.0, 5500.0, 4800.0, 4200.0, 5200.0, 5500.0, 5000.0, 3500.0, 4200.0, 5000.0, 6000.0, 3900.0]
<class 'float'>
cargo: ['Analista', 'Gerente', 'Supervisor', 'Diretor', 'Analista', 'Coordenador', 'Gerente', 'Assistente', 'Analista', 'Coordenador', 'Supervisor', 'Assistente', 'Gerente', 'Coordenador']
<class 'str'>

In [ ]:
dados_tratados_novo = [["nome", "idade", "salario", "cargo"]]
for i in range(len(nome)):
    dados_tratados_novo.append([nome[i], idade[i], salario[i], cargo[i]])
#print(dados_tratados_novo)

for index,linha in enumerate(dados_tratados_novo):
  print(index,linha)

0 ['nome', 'idade', 'salario', 'cargo']
1 ['Carlos', 34, 3500.0, 'Analista']
2 ['Maria', 45, 4500.0, 'Gerente']
3 ['Paula', 29, 4200.0, 'Supervisor']
4 ['Renato', 56, 5500.0, 'Diretor']
5 ['Marcelo', 41, 4800.0, 'Analista']
6 ['Luciana', 25, 4200.0, 'Coordenador']
7 ['Ricardo', 38, 5200.0, 'Gerente']
8 ['Adriana', 43, 5500.0, 'Assistente']
9 ['Camila', 34, 5000.0, 'Analista']
10 ['Paulo', 22, 3500.0, 'Coordenador']
11 ['Carla', 41, 4200.0, 'Supervisor']
12 ['Eduardo', 50, 5000.0, 'Assistente']
13 ['Larissa', 35, 6000.0, 'Gerente']
14 ['Mário', 28, 3900.0, 'Coordenador']

In [ ]:
df = pd.DataFrame({
    'nome': nome,
    'idade': idade,
    'salario': salario,
    'cargo': cargo
})

In [ ]:
df.head(14)

       nome  idade  salario        cargo
0    Carlos     34   3500.0     Analista
1     Maria     45   4500.0      Gerente
2     Paula     29   4200.0   Supervisor
3    Renato     56   5500.0      Diretor
4   Marcelo     41   4800.0     Analista
5   Luciana     25   4200.0  Coordenador
6   Ricardo     38   5200.0      Gerente
7   Adriana     43   5500.0   Assistente
8    Camila     34   5000.0     Analista
9     Paulo     22   3500.0  Coordenador
10    Carla     41   4200.0   Supervisor
11  Eduardo     50   5000.0   Assistente
12  Larissa     35   6000.0      Gerente
13    Mário     28   3900.0  Coordenador

In [ ]:
df.to_csv('dados_tratados.csv',index = False)

In [ ]:
from google.colab import auth
auth.authenticate_user()

project_id = "quixotic-strand-454923-q7"
!gcloud config set project {project_id}

from google.cloud import storage
client = storage.Client()

bucket_name = 'projeto-kauane-prisco-1'
bucket = client.bucket(bucket_name)

df.to_csv('dados_tratados.csv', index=False)

source_file_name = 'dados_tratados.csv'
destination_blob_name = 'dados-tratados/dados_tratados.csv'

blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

print(f"Arquivo {source_file_name} enviado para {destination_blob_name} no bucket {bucket_name}.")

Updated property [core/project].
Arquivo dados_tratados.csv enviado para dados-tratados/dados_tratados.csv no bucket projeto-kauane-prisco-1.

In [ ]:
dados_tratados = pd.read_csv('https://storage.googleapis.com/projeto-kauane-prisco-1/dados-tratados/dados_tratados.csv')
display(dados_tratados)

       nome  idade  salario        cargo
0    Carlos     34   3500.0     Analista
1     Maria     45   4500.0      Gerente
2     Paula     29   4200.0   Supervisor
3    Renato     56   5500.0      Diretor
4   Marcelo     41   4800.0     Analista
5   Luciana     25   4200.0  Coordenador
6   Ricardo     38   5200.0      Gerente
7   Adriana     43   5500.0   Assistente
8    Camila     34   5000.0     Analista
9     Paulo     22   3500.0  Coordenador
10    Carla     41   4200.0   Supervisor
11  Eduardo     50   5000.0   Assistente
12  Larissa     35   6000.0      Gerente
13    Mário     28   3900.0  Coordenador