<a href="https://colab.research.google.com/github/KahPrisco/Bootcamp/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''01. Quantos registros existem na base de dados?

02. Quantos registros possuem valores ausentes?

03. Substitua os valores ausentes na coluna "Valor da Venda" pela média das vendas e exiba a nova média.

04. Converta todos os valores da coluna "Categoria" para letras maiúsculas.

05. Qual é o maior valor de venda e qual produto foi vendido por esse valor?

06. Quantos pedidos foram feitos para cada categoria de produto?

07. Qual é a média de preço dos produtos por categoria?

08. Liste os produtos únicos da base de dados.

09. Crie uma nova coluna chamada "Ano da Venda" que armazena o ano em que a venda foi realizada.

10. Liste os 5 produtos mais vendidos.

11. Quantos pedidos foram feitos por cada método de pagamento?

12. Qual é o faturamento total por categoria de produto?

13. Liste os 5 clientes que mais gastaram em compras.

14. Existe algum registro sem informação de produto? Liste-os.

15. Crie uma nova coluna "Faixa de Preço" usando a coluna "Preço Unitário" para classificar os produtos como:

Baixo (preço < 50)
Médio (50 ≤ preço ≤ 300)
Alto (preço > 300)

16.
Crie uma nova coluna "Status Simplificado" para transformar a coluna "Status do Pedido":
"Entregue" → "Finalizado"
"Em andamento" → "Processando"
"Cancelado" → "Cancelado"

17. Crie uma nova coluna "Preço com Desconto", aplicando 10% de desconto sobre o valor original da venda.

18. Quantos produtos estão na faixa de preço "Alto"?

19. Use dropna() para excluir registros com valoresausentes e salve o DataFrame limpo em um novo arquivo CSV.

20. Faça a alteração da coluna "Quantidade Vendida" para o tipo inteiro e exiba o DataFrame.'''

'01. Quantos registros existem na base de dados?\n\n02. Quantos registros possuem valores ausentes?\n\n03. Substitua os valores ausentes na coluna "Valor da Venda" pela média das vendas e exiba a nova média.\n\n04. Converta todos os valores da coluna "Categoria" para letras maiúsculas.\n\n05. Qual é o maior valor de venda e qual produto foi vendido por esse valor?\n\n06. Quantos pedidos foram feitos para cada categoria de produto?\n\n07. Qual é a média de preço dos produtos por categoria?\n\n08. Liste os produtos únicos da base de dados.\n\n09. Crie uma nova coluna chamada "Ano da Venda" que armazena o ano em que a venda foi realizada.\n\n10. Liste os 5 produtos mais vendidos.\n\n11. Quantos pedidos foram feitos por cada método de pagamento?\n\n12. Qual é o faturamento total por categoria de produto?\n\n13. Liste os 5 clientes que mais gastaram em compras.\n\n14. Existe algum registro sem informação de produto? Liste-os.\n\n15. Crie uma nova coluna "Faixa de Preço" usando a coluna "Preço Unitário" para classificar os produtos como:\n\nBaixo (preço < 50)\nMédio (50 ≤ preço ≤ 300)\nAlto (preço > 300)\n\n16.\nCrie uma nova coluna "Status Simplificado" para transformar a coluna "Status do Pedido":\n"Entregue" → "Finalizado"\n"Em andamento" → "Processando"\n"Cancelado" → "Cancelado"\n\n17. Crie uma nova coluna "Preço com Desconto", aplicando 10% de desconto sobre o valor original da venda.\n\n18. Quantos produtos estão na faixa de preço "Alto"?\n\n19. Use dropna() para excluir registros com valoresausentes e salve o DataFrame limpo em um novo arquivo CSV.\n\n20. Faça a alteração da coluna "Quantidade Vendida" para o tipo inteiro e exiba o DataFrame.'

#Base de dados

In [ ]:
'''LINK DA BASE: https://drive.google.com/uc?export=download&id=1A8pS9Oeg2i2_gEC0o-J6bTuxfh6T2YNU'''

'LINK DA BASE: https://drive.google.com/uc?export=download&id=1A8pS9Oeg2i2_gEC0o-J6bTuxfh6T2YNU'

## 01. Quantos registros existem na base de dados?

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(' https://drive.google.com/uc?export=download&id=1A8pS9Oeg2i2_gEC0o-J6bTuxfh6T2YNU')
df.head()

,ID_Venda,Produto,Categoria,Quantidade Vendida,Preço Unitário,Valor da Venda,Método de Pagamento,Status do Pedido,Cliente_ID,Data da Venda
0,1,Smartphone,Eletrônicos,5,2056,10280.0,NaN,Entregue,1094,2025-02-07
1,2,SSD,Eletrônicos,10,3506,35060.0,Cartão de Crédito,Entregue,1011,2024-12-10
2,3,Mouse,Eletrônicos,9,1678,15102.0,Transferência Bancária,Entregue,1057,2024-06-03
3,4,Monitor,Eletrônicos,3,3512,NaN,Pix,Em andamento,1019,2024-12-11
4,5,Cadeira Gamer,Eletrônicos,2,3162,6324.0,NaN,Em andamento,1044,2024-05-26

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Venda             100 non-null    int64
 1   Produto              90 non-null     object
 2   Categoria            100 non-null    object
 3   Quantidade Vendida   100 non-null    int64
 4   Preço Unitário       100 non-null    int64
 5   Valor da Venda       90 non-null     float64
 6   Método de Pagamento  90 non-null     object
 7   Status do Pedido     90 non-null     object
 8   Cliente_ID           100 non-null    int64
 9   Data da Venda        100 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.9+ KB

In [ ]:
#(Linhas, Colunas)
df.shape

(100, 10)

##02. Quantos registros possuem valores ausentes?

In [ ]:
print(df.isna())

    ID_Venda  Produto  Categoria  Quantidade Vendida  Preço Unitário  \
0      False    False      False               False           False
1      False    False      False               False           False
2      False    False      False               False           False
3      False    False      False               False           False
4      False    False      False               False           False
..       ...      ...        ...                 ...             ...
95     False    False      False               False           False
96     False    False      False               False           False
97     False     True      False               False           False
98     False    False      False               False           False
99     False     True      False               False           False

    Valor da Venda  Método de Pagamento  Status do Pedido  Cliente_ID  \
0            False                 True             False       False
1            False                False             False       False
2            False                False             False       False
3             True                False             False       False
4            False                 True             False       False
..             ...                  ...               ...         ...
95            True                False             False       False
96           False                False             False       False
97           False                False              True       False
98            True                False             False       False
99           False                False             False       False

    Data da Venda
0           False
1           False
2           False
3           False
4           False
..            ...
95          False
96          False
97          False
98          False
99          False

[100 rows x 10 columns]

In [ ]:
print(df.isna().sum())

ID_Venda                0
Produto                10
Categoria               0
Quantidade Vendida      0
Preço Unitário          0
Valor da Venda         10
Método de Pagamento    10
Status do Pedido       10
Cliente_ID              0
Data da Venda           0
dtype: int64

##03. Substitua os valores ausentes na coluna "Valor da Venda" pela média das vendas e exiba a nova média.

In [ ]:
df['Valor da Venda'].mean()

np.float64(14619.422222222222)

In [ ]:
df['Valor da Venda'] = df['Valor da Venda'].fillna(df['Valor da Venda'].mean()).round()
df.head()

,ID_Venda,Produto,Categoria,Quantidade Vendida,Preço Unitário,Valor da Venda,Método de Pagamento,Status do Pedido,Cliente_ID,Data da Venda
0,1,Smartphone,Eletrônicos,5,2056,10280.0,NaN,Entregue,1094,2025-02-07
1,2,SSD,Eletrônicos,10,3506,35060.0,Cartão de Crédito,Entregue,1011,2024-12-10
2,3,Mouse,Eletrônicos,9,1678,15102.0,Transferência Bancária,Entregue,1057,2024-06-03
3,4,Monitor,Eletrônicos,3,3512,14619.0,Pix,Em andamento,1019,2024-12-11
4,5,Cadeira Gamer,Eletrônicos,2,3162,6324.0,NaN,Em andamento,1044,2024-05-26

In [ ]:
print(df.isna().sum())

ID_Venda                0
Produto                10
Categoria               0
Quantidade Vendida      0
Preço Unitário          0
Valor da Venda          0
Método de Pagamento    10
Status do Pedido       10
Cliente_ID              0
Data da Venda           0
dtype: int64

In [ ]:
df['Valor da Venda'].mean()

np.float64(14619.38)

## 04. Converta todos os valores da coluna "Categoria" para letras maiúsculas.

In [ ]:
df["Categoria"] = df["Categoria"].str.upper()

In [ ]:
df[["Categoria"]].head()

     Categoria
0  ELETRÔNICOS
1  ELETRÔNICOS
2  ELETRÔNICOS
3  ELETRÔNICOS
4  ELETRÔNICOS

## 05. Qual é o maior valor de venda e qual produto foi vendido por esse valor?

In [ ]:
df.sort_values(['Valor da Venda'], inplace = True, ascending = False)
display(df)

,ID_Venda,Produto,Categoria,Quantidade Vendida,Preço Unitário,Valor da Venda,Método de Pagamento,Status do Pedido,Cliente_ID,Data da Venda
77,78,Notebook,PERIFÉRICOS,10,4673,46730.0,Cartão de Crédito,Entregue,1082,2024-08-24
24,25,Cadeira Gamer,ELETRÔNICOS,10,4587,45870.0,Boleto,Cancelado,1028,2025-03-28
58,59,Impressora,ELETRÔNICOS,9,4460,40140.0,NaN,Em andamento,1055,2025-02-24
34,35,Monitor,PERIFÉRICOS,9,4036,36324.0,NaN,Entregue,1037,2024-12-10
56,57,Notebook,ELETRÔNICOS,10,3609,36090.0,Pix,Cancelado,1100,2024-10-22
...,...,...,...,...,...,...,...,...,...,...
91,92,Placa de Vídeo,MÓVEIS,9,133,1197.0,Boleto,Entregue,1030,2024-09-04
47,48,SSD,PERIFÉRICOS,9,129,1161.0,Cartão de Crédito,Entregue,1088,2025-01-14
14,15,SSD,PERIFÉRICOS,2,435,870.0,NaN,Entregue,1080,2025-01-09
74,75,Notebook,PERIFÉRICOS,8,98,784.0,Pix,Em andamento,1096,2024-09-13
33,34,Notebook,ACESSÓRIOS,7,67,469.0,Transferência Bancária,Em andamento,1100,2024-08-11

In [ ]:
df.sort_values(['Valor da Venda'], inplace=True, ascending=False)
display(df[["Valor da Venda", "Produto"]])

    Valor da Venda         Produto
77         46730.0        Notebook
24         45870.0   Cadeira Gamer
58         40140.0      Impressora
34         36324.0         Monitor
56         36090.0        Notebook
..             ...             ...
91          1197.0  Placa de Vídeo
47          1161.0             SSD
14           870.0             SSD
74           784.0        Notebook
33           469.0        Notebook

[100 rows x 2 columns]

In [ ]:
df.sort_values(['Valor da Venda'], inplace=True, ascending=False)
Maior_valor = df.head(1)
print(Maior_valor[['Valor da Venda', 'Produto']])

    Valor da Venda   Produto
77         46730.0  Notebook

## 06. Quantos pedidos foram feitos para cada categoria de produto?

In [ ]:
df["Categoria"].value_counts().reset_index()

     Categoria  count
0   ACESSÓRIOS     27
1  ELETRÔNICOS     25
2       MÓVEIS     25
3  PERIFÉRICOS     23

In [ ]:
df.groupby("Categoria")["Quantidade Vendida"].sum().reset_index()

     Categoria  Quantidade Vendida
0   ACESSÓRIOS                 163
1  ELETRÔNICOS                 166
2       MÓVEIS                 146
3  PERIFÉRICOS                 122

##  07. Qual é a média de preço dos produtos por categoria?

In [ ]:
df.groupby("Categoria")["Preço Unitário"].mean().reset_index()

     Categoria  Preço Unitário
0   ACESSÓRIOS     2382.259259
1  ELETRÔNICOS     2838.080000
2       MÓVEIS     2086.440000
3  PERIFÉRICOS     2346.086957

## 08. Liste os produtos únicos da base de dados.

In [ ]:
df["Produto"].unique()

array(['Notebook', 'Cadeira Gamer', 'Impressora', 'Monitor', 'SSD', nan,
       'Mouse', 'Placa de Vídeo', 'Headset', 'Teclado', 'Smartphone'],
      dtype=object)

In [ ]:
df["Produto"].dropna().unique()

array(['Notebook', 'Cadeira Gamer', 'Impressora', 'Monitor', 'SSD',
       'Mouse', 'Placa de Vídeo', 'Headset', 'Teclado', 'Smartphone'],
      dtype=object)

## 09. Crie uma nova coluna chamada "Ano da Venda" que armazena o ano em que a venda foi realizada.

In [ ]:
df['Ano da Venda'] = pd.to_datetime(df['Data da Venda']).dt.year
display(df)

,ID_Venda,Produto,Categoria,Quantidade Vendida,Preço Unitário,Valor da Venda,Método de Pagamento,Status do Pedido,Cliente_ID,Data da Venda,Ano da Venda
77,78,Notebook,PERIFÉRICOS,10,4673,46730.0,Cartão de Crédito,Entregue,1082,2024-08-24,2024
24,25,Cadeira Gamer,ELETRÔNICOS,10,4587,45870.0,Boleto,Cancelado,1028,2025-03-28,2025
58,59,Impressora,ELETRÔNICOS,9,4460,40140.0,NaN,Em andamento,1055,2025-02-24,2025
34,35,Monitor,PERIFÉRICOS,9,4036,36324.0,NaN,Entregue,1037,2024-12-10,2024
56,57,Notebook,ELETRÔNICOS,10,3609,36090.0,Pix,Cancelado,1100,2024-10-22,2024
...,...,...,...,...,...,...,...,...,...,...,...
91,92,Placa de Vídeo,MÓVEIS,9,133,1197.0,Boleto,Entregue,1030,2024-09-04,2024
47,48,SSD,PERIFÉRICOS,9,129,1161.0,Cartão de Crédito,Entregue,1088,2025-01-14,2025
14,15,SSD,PERIFÉRICOS,2,435,870.0,NaN,Entregue,1080,2025-01-09,2025
74,75,Notebook,PERIFÉRICOS,8,98,784.0,Pix,Em andamento,1096,2024-09-13,2024
33,34,Notebook,ACESSÓRIOS,7,67,469.0,Transferência Bancária,Em andamento,1100,2024-08-11,2024

## 10. Liste os 5 produtos mais vendidos.

In [ ]:
df.groupby("Produto")["Quantidade Vendida"].sum().reset_index()

          Produto  Quantidade Vendida
0   Cadeira Gamer                  70
1         Headset                  41
2      Impressora                  84
3         Monitor                  74
4           Mouse                  36
5        Notebook                  86
6  Placa de Vídeo                  18
7             SSD                  50
8      Smartphone                  68
9         Teclado                  22

In [ ]:
df.groupby("Produto")["Quantidade Vendida"].sum().reset_index().sort_values("Quantidade Vendida", ascending=False).head(5)

         Produto  Quantidade Vendida
5       Notebook                  86
2     Impressora                  84
3        Monitor                  74
0  Cadeira Gamer                  70
8     Smartphone                  68

## 11. Quantos pedidos foram feitos por cada método de pagamento?

In [ ]:
df.groupby("Método de Pagamento")['Quantidade Vendida'].sum().reset_index()

      Método de Pagamento  Quantidade Vendida
0                  Boleto                 148
1       Cartão de Crédito                 152
2                     Pix                 150
3  Transferência Bancária                  98

In [ ]:
df.groupby("Método de Pagamento")['ID_Venda'].count().reset_index()

      Método de Pagamento  ID_Venda
0                  Boleto        24
1       Cartão de Crédito        23
2                     Pix        26
3  Transferência Bancária        17

## 12. Qual é o faturamento total por categoria de produto?

In [ ]:
df.groupby("Categoria")["Valor da Venda"].sum().reset_index()

     Categoria  Valor da Venda
0   ACESSÓRIOS        355695.0
1  ELETRÔNICOS        466119.0
2       MÓVEIS        360313.0
3  PERIFÉRICOS        279811.0

## 13. Liste os 5 clientes que mais gastaram em compras.

In [ ]:
df.groupby("ID_Venda")["Valor da Venda"].sum().reset_index()

    ID_Venda  Valor da Venda
0          1         10280.0
1          2         35060.0
2          3         15102.0
3          4         14619.0
4          5          6324.0
..       ...             ...
95        96         14619.0
96        97         16064.0
97        98          3280.0
98        99         14619.0
99       100          7120.0

[100 rows x 2 columns]

In [ ]:
df.groupby("ID_Venda")["Valor da Venda"].sum().reset_index().sort_values("Valor da Venda", ascending=False).head(5)

    ID_Venda  Valor da Venda
77        78         46730.0
24        25         45870.0
58        59         40140.0
34        35         36324.0
56        57         36090.0

## 14. Existe algum registro sem informação de produto? Liste-os.

In [ ]:
 df[df['Produto'].isna() | df['Produto'].eq('')]

,ID_Venda,Produto,Categoria,Quantidade Vendida,Preço Unitário,Valor da Venda,Método de Pagamento,Status do Pedido,Cliente_ID,Data da Venda,Ano da Venda
68,69,NaN,ACESSÓRIOS,8,4401,35208.0,Pix,Em andamento,1078,2024-07-16,2024
70,71,NaN,PERIFÉRICOS,4,2299,14619.0,Transferência Bancária,Entregue,1091,2024-11-05,2024
65,66,NaN,ELETRÔNICOS,8,3445,14619.0,Boleto,Cancelado,1089,2024-09-16,2024
69,70,NaN,PERIFÉRICOS,3,3938,11814.0,Transferência Bancária,Em andamento,1096,2024-11-25,2024
99,100,NaN,ACESSÓRIOS,8,890,7120.0,Cartão de Crédito,Cancelado,1036,2024-08-03,2024
81,82,NaN,ELETRÔNICOS,4,1683,6732.0,Cartão de Crédito,Cancelado,1019,2024-11-29,2024
12,13,NaN,PERIFÉRICOS,3,2219,6657.0,Boleto,Entregue,1095,2024-06-17,2024
66,67,NaN,PERIFÉRICOS,4,1258,5032.0,Cartão de Crédito,Entregue,1099,2024-08-26,2024
64,65,NaN,ACESSÓRIOS,4,1257,5028.0,Cartão de Crédito,Entregue,1031,2024-07-31,2024
97,98,NaN,MÓVEIS,2,1640,3280.0,Pix,NaN,1046,2024-12-30,2024

In [ ]:
df[df["Produto"].isna() | (df["Produto"] == "")]

,ID_Venda,Produto,Categoria,Quantidade Vendida,Preço Unitário,Valor da Venda,Método de Pagamento,Status do Pedido,Cliente_ID,Data da Venda,Ano da Venda
68,69,NaN,ACESSÓRIOS,8,4401,35208.0,Pix,Em andamento,1078,2024-07-16,2024
70,71,NaN,PERIFÉRICOS,4,2299,14619.0,Transferência Bancária,Entregue,1091,2024-11-05,2024
65,66,NaN,ELETRÔNICOS,8,3445,14619.0,Boleto,Cancelado,1089,2024-09-16,2024
69,70,NaN,PERIFÉRICOS,3,3938,11814.0,Transferência Bancária,Em andamento,1096,2024-11-25,2024
99,100,NaN,ACESSÓRIOS,8,890,7120.0,Cartão de Crédito,Cancelado,1036,2024-08-03,2024
81,82,NaN,ELETRÔNICOS,4,1683,6732.0,Cartão de Crédito,Cancelado,1019,2024-11-29,2024
12,13,NaN,PERIFÉRICOS,3,2219,6657.0,Boleto,Entregue,1095,2024-06-17,2024
66,67,NaN,PERIFÉRICOS,4,1258,5032.0,Cartão de Crédito,Entregue,1099,2024-08-26,2024
64,65,NaN,ACESSÓRIOS,4,1257,5028.0,Cartão de Crédito,Entregue,1031,2024-07-31,2024
97,98,NaN,MÓVEIS,2,1640,3280.0,Pix,NaN,1046,2024-12-30,2024

In [ ]:
df["Produto"].isna().sum()

np.int64(10)

## 15. Crie uma nova coluna "Faixa de Preço" usando a coluna "Preço Unitário" para classificar os produtos como:

## Baixo (preço < 50)
## Médio (50 ≤ preço ≤ 300)
## Alto (preço > 300)

In [ ]:
df.loc[df['Preço Unitário'] < 50, 'Faixa de Preço'] = 'Baixo'
df.loc[(df['Preço Unitário'] >= 50) & (df['Preço Unitário'] <= 300), 'Faixa de Preço'] = 'Médio'
df.loc[df['Preço Unitário'] > 300, 'Faixa de Preço'] = 'Alto'
display(df)

,ID_Venda,Produto,Categoria,Quantidade Vendida,Preço Unitário,Valor da Venda,Método de Pagamento,Status do Pedido,Cliente_ID,Data da Venda,Ano da Venda,Faixa de Preço
77,78,Notebook,PERIFÉRICOS,10,4673,46730.0,Cartão de Crédito,Entregue,1082,2024-08-24,2024,Alto
24,25,Cadeira Gamer,ELETRÔNICOS,10,4587,45870.0,Boleto,Cancelado,1028,2025-03-28,2025,Alto
58,59,Impressora,ELETRÔNICOS,9,4460,40140.0,NaN,Em andamento,1055,2025-02-24,2025,Alto
34,35,Monitor,PERIFÉRICOS,9,4036,36324.0,NaN,Entregue,1037,2024-12-10,2024,Alto
56,57,Notebook,ELETRÔNICOS,10,3609,36090.0,Pix,Cancelado,1100,2024-10-22,2024,Alto
...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,Placa de Vídeo,MÓVEIS,9,133,1197.0,Boleto,Entregue,1030,2024-09-04,2024,Médio
47,48,SSD,PERIFÉRICOS,9,129,1161.0,Cartão de Crédito,Entregue,1088,2025-01-14,2025,Médio
14,15,SSD,PERIFÉRICOS,2,435,870.0,NaN,Entregue,1080,2025-01-09,2025,Alto
74,75,Notebook,PERIFÉRICOS,8,98,784.0,Pix,Em andamento,1096,2024-09-13,2024,Médio
33,34,Notebook,ACESSÓRIOS,7,67,469.0,Transferência Bancária,Em andamento,1100,2024-08-11,2024,Médio

In [ ]:
df["Faixa de Preço"].value_counts().reset_index()

  Faixa de Preço  count
0           Alto     94
1          Médio      6

##16.Crie uma nova coluna "Status Simplificado" para transformar a coluna "Status do Pedido":
##"Entregue" → "Finalizado"
##"Em andamento" → "Processando"
##"Cancelado" → "Cancelado"

In [ ]:
df.loc[df['Status do Pedido'] == 'Entregue', 'Status Simplificado'] = 'Finalizado'
df.loc[df['Status do Pedido'] == 'Em andamento', 'Status Simplificado'] = 'Processando'
df.loc[df['Status do Pedido'] == 'Cancelado', 'Status Simplificado'] = 'Cancelado'
df.loc[df['Status do Pedido'].isnull(), 'Status Simplificado'] = 'Desconhecido'
df.head()

,ID_Venda,Produto,Categoria,Quantidade Vendida,Preço Unitário,Valor da Venda,Método de Pagamento,Status do Pedido,Cliente_ID,Data da Venda,Ano da Venda,Faixa de Preço,Status Simplificado
77,78,Notebook,PERIFÉRICOS,10,4673,46730.0,Cartão de Crédito,Entregue,1082,2024-08-24,2024,Alto,Finalizado
24,25,Cadeira Gamer,ELETRÔNICOS,10,4587,45870.0,Boleto,Cancelado,1028,2025-03-28,2025,Alto,Cancelado
58,59,Impressora,ELETRÔNICOS,9,4460,40140.0,NaN,Em andamento,1055,2025-02-24,2025,Alto,Processando
34,35,Monitor,PERIFÉRICOS,9,4036,36324.0,NaN,Entregue,1037,2024-12-10,2024,Alto,Finalizado
56,57,Notebook,ELETRÔNICOS,10,3609,36090.0,Pix,Cancelado,1100,2024-10-22,2024,Alto,Cancelado

## 17. Crie uma nova coluna "Preço com Desconto", aplicando 10% de desconto sobre o valor original da venda.

In [ ]:
df['Preço com Desconto'] = round(df['Valor da Venda'] - (df['Valor da Venda'] * 10 / 100), 2)
df.head()

,ID_Venda,Produto,Categoria,Quantidade Vendida,Preço Unitário,Valor da Venda,Método de Pagamento,Status do Pedido,Cliente_ID,Data da Venda,Ano da Venda,Faixa de Preço,Status Simplificado,Preço com Desconto
77,78,Notebook,PERIFÉRICOS,10,4673,46730.0,Cartão de Crédito,Entregue,1082,2024-08-24,2024,Alto,Finalizado,42057.0
24,25,Cadeira Gamer,ELETRÔNICOS,10,4587,45870.0,Boleto,Cancelado,1028,2025-03-28,2025,Alto,Cancelado,41283.0
58,59,Impressora,ELETRÔNICOS,9,4460,40140.0,NaN,Em andamento,1055,2025-02-24,2025,Alto,Processando,36126.0
34,35,Monitor,PERIFÉRICOS,9,4036,36324.0,NaN,Entregue,1037,2024-12-10,2024,Alto,Finalizado,32691.6
56,57,Notebook,ELETRÔNICOS,10,3609,36090.0,Pix,Cancelado,1100,2024-10-22,2024,Alto,Cancelado,32481.0

## 18. Quantos produtos estão na faixa de preço "Alto"?

In [ ]:
df[df["Faixa de Preço"] == "Alto"]["Faixa de Preço"].value_counts().reset_index()

  Faixa de Preço  count
0           Alto     94

## 19. Use dropna() para excluir registros com valoresausentes e salve o DataFrame limpo em um novo arquivo CSV.

In [ ]:
import csv
dados_tratados = df.dropna()
dados_tratados.to_csv("dados_tratados.csv",index=False)

In [ ]:
dados_tratados.head()

,ID_Venda,Produto,Categoria,Quantidade Vendida,Preço Unitário,Valor da Venda,Método de Pagamento,Status do Pedido,Cliente_ID,Data da Venda,Ano da Venda,Faixa de Preço,Status Simplificado,Preço com Desconto
77,78,Notebook,PERIFÉRICOS,10,4673,46730.0,Cartão de Crédito,Entregue,1082,2024-08-24,2024,Alto,Finalizado,42057.0
24,25,Cadeira Gamer,ELETRÔNICOS,10,4587,45870.0,Boleto,Cancelado,1028,2025-03-28,2025,Alto,Cancelado,41283.0
56,57,Notebook,ELETRÔNICOS,10,3609,36090.0,Pix,Cancelado,1100,2024-10-22,2024,Alto,Cancelado,32481.0
13,14,SSD,MÓVEIS,10,3559,35590.0,Transferência Bancária,Em andamento,1028,2025-01-20,2025,Alto,Processando,32031.0
5,6,Monitor,ELETRÔNICOS,8,4442,35536.0,Cartão de Crédito,Em andamento,1010,2024-06-22,2024,Alto,Processando,31982.4

In [ ]:
dados_tratados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 71 entries, 77 to 33
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Venda             71 non-null     int64
 1   Produto              71 non-null     object
 2   Categoria            71 non-null     object
 3   Quantidade Vendida   71 non-null     int64
 4   Preço Unitário       71 non-null     int64
 5   Valor da Venda       71 non-null     float64
 6   Método de Pagamento  71 non-null     object
 7   Status do Pedido     71 non-null     object
 8   Cliente_ID           71 non-null     int64
 9   Data da Venda        71 non-null     object
 10  Ano da Venda         71 non-null     int32
 11  Faixa de Preço       71 non-null     object
 12  Status Simplificado  71 non-null     object
 13  Preço com Desconto   71 non-null     float64
dtypes: float64(2), int32(1), int64(4), object(7)
memory usage: 10.1+ KB

In [ ]:
print(dados_tratados.isna().sum())

ID_Venda               0
Produto                0
Categoria              0
Quantidade Vendida     0
Preço Unitário         0
Valor da Venda         0
Método de Pagamento    0
Status do Pedido       0
Cliente_ID             0
Data da Venda          0
Ano da Venda           0
Faixa de Preço         0
Status Simplificado    0
Preço com Desconto     0
dtype: int64

In [ ]:
dados_tratados.shape

(71, 14)

## 20. Faça a alteração da coluna "Quantidade Vendida" para o tipo inteiro e exiba o DataFrame.

In [ ]:
dados_tratados["Quantidade Vendida"] = dados_tratados["Quantidade Vendida"].astype(int)
display(dados_tratados)

<ipython-input-43-6a586f1e1874>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tratados["Quantidade Vendida"] = dados_tratados["Quantidade Vendida"].astype(int)

,ID_Venda,Produto,Categoria,Quantidade Vendida,Preço Unitário,Valor da Venda,Método de Pagamento,Status do Pedido,Cliente_ID,Data da Venda,Ano da Venda,Faixa de Preço,Status Simplificado,Preço com Desconto
77,78,Notebook,PERIFÉRICOS,10,4673,46730.0,Cartão de Crédito,Entregue,1082,2024-08-24,2024,Alto,Finalizado,42057.0
24,25,Cadeira Gamer,ELETRÔNICOS,10,4587,45870.0,Boleto,Cancelado,1028,2025-03-28,2025,Alto,Cancelado,41283.0
56,57,Notebook,ELETRÔNICOS,10,3609,36090.0,Pix,Cancelado,1100,2024-10-22,2024,Alto,Cancelado,32481.0
13,14,SSD,MÓVEIS,10,3559,35590.0,Transferência Bancária,Em andamento,1028,2025-01-20,2025,Alto,Processando,32031.0
5,6,Monitor,ELETRÔNICOS,8,4442,35536.0,Cartão de Crédito,Em andamento,1010,2024-06-22,2024,Alto,Processando,31982.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,20,Notebook,MÓVEIS,8,209,1672.0,Cartão de Crédito,Em andamento,1039,2024-11-29,2024,Médio,Processando,1504.8
91,92,Placa de Vídeo,MÓVEIS,9,133,1197.0,Boleto,Entregue,1030,2024-09-04,2024,Médio,Finalizado,1077.3
47,48,SSD,PERIFÉRICOS,9,129,1161.0,Cartão de Crédito,Entregue,1088,2025-01-14,2025,Médio,Finalizado,1044.9
74,75,Notebook,PERIFÉRICOS,8,98,784.0,Pix,Em andamento,1096,2024-09-13,2024,Médio,Processando,705.6
33,34,Notebook,ACESSÓRIOS,7,67,469.0,Transferência Bancária,Em andamento,1100,2024-08-11,2024,Médio,Processando,422.1